global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9100'] ## only for demo purposes don't use host.docker.internal in production
